### ISSUE TITLE
Add code of conduct and security

### ISSUE THREAD

**Issue by fcollonval** [jupyter/.github#2]
@jtpio @afshin 

It seems that there is no code of conduct nor security policy for notebook - probably a consequence of moving the master branch to v7. Would it make sense to add them here as for the jupyterlab organization?

**Comment by jtpio** [comment]
Thanks @fcollonval.

> Would it make sense to add them here as for the jupyterlab organization?

I think this sounds good yes.

**Comment by fcollonval** [comment]
@jtpio would you mind starting the repository? With my rights it seems I cannot start opening PR's on this repository.

**Comment by jtpio** [comment]
@fcollonval I just created a `README.md` file, which should enable forking for this repo.
